### ISSUE TITLE
Expose underlying Key (GUID) for the IPublishedContent

### ISSUE THREAD

**Issue by ryanlewis** [modelsbuilder/ModelsBuilder.Original#118]
At the moment you automatically get an `Id` (along with `Name`, etc.). Expose the underlying GUID (possibly as `.Key`) that was introduced in 7.3/7.4. 

At the moment, obtaining this is really unintuitive, and seems to require the following:

```
var item = Model.Content.Unwrap() as IPublishedContentWithKey;
var key = item.GetKey();
```

**Comment by HarveyWilliams** [comment]
This seems to have been fixed at some point.

These days, Models Builder models inherit from `PublishedContentModel` which inherit don until the `.GetKey()` method is available.
